databases:
  - name: cinema-app
    databaseName: cinemaapp
    user: cinemaapp
    ipAllowList: []
    plan: free
  
services:
  - type: web
    name: cinema-app
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinema-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
